/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "dtracker.h"


/***************************************
 ***************************************/

FD_dtracker *
create_form_dtracker( void )
{
    FL_OBJECT *obj;
    FD_dtracker *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->dtracker = fl_bgn_form( FL_NO_BOX, 435, 307 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 435, 307, "Doppler Tracker" );
    fl_set_object_color( obj, FL_INDIANRED, FL_COL1 );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );

    fdui->track_set = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 20, 10, 140, 30, "Track Doppler" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, set_tracking, 0 );

    fdui->latitude = obj = fl_add_input( FL_NORMAL_INPUT, 130, 50, 150, 30, "Current Latitude" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, set_latitude, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->tracked_ra = obj = fl_add_input( FL_NORMAL_INPUT, 130, 100, 150, 30, "Tracking RA" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, set_tracking_ra, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->tracking_dec = obj = fl_add_input( FL_NORMAL_INPUT, 130, 150, 150, 30, "Tracking DEC" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, set_tracking_dec, 0 );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->current_lmst = obj = fl_add_text( FL_NORMAL_TEXT, 130, 200, 150, 30, "" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_DARKCYAN, FL_MCOL );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 200, 80, 30, "LMST" );
    fl_set_object_color( obj, FL_INDIANRED, FL_MCOL );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->current_doppler = obj = fl_add_text( FL_NORMAL_TEXT, 130, 240, 150, 30, "" );
    fl_set_object_boxtype( obj, FL_EMBOSSED_BOX );
    fl_set_object_color( obj, FL_DARKCYAN, FL_MCOL );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 240, 90, 30, "CORRECTION" );
    fl_set_object_color( obj, FL_INDIANRED, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->help_button = obj = fl_add_button( FL_NORMAL_BUTTON, 320, 270, 90, 30, "HELP" );
    fl_set_object_color( obj, FL_SLATEBLUE, FL_COL1 );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, do_help, 0 );

    fl_end_form( );

    fdui->dtracker->fdui = fdui;

    return fdui;
}
