/* Header file generated by fdesign on Wed Jun  8 20:19:45 2011 */

#ifndef FD_dtracker_h_
#define FD_dtracker_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void set_tracking( FL_OBJECT *, long );
extern void set_latitude( FL_OBJECT *, long );
extern void set_tracking_ra( FL_OBJECT *, long );
extern void set_tracking_dec( FL_OBJECT *, long );
extern void do_help( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * dtracker;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * track_set;
    FL_OBJECT * latitude;
    FL_OBJECT * tracked_ra;
    FL_OBJECT * tracking_dec;
    FL_OBJECT * current_lmst;
    FL_OBJECT * current_doppler;
    FL_OBJECT * help_button;
} FD_dtracker;

extern FD_dtracker * create_form_dtracker( void );

#endif /* FD_dtracker_h_ */
